home work #6
DeliriumInTheVoid/r_d_cpp_gamedev pull request #6
Opened 2023-07-01 19:54 UTC by DeliriumInTheVoid

2023-07-07 16:31 UTC, helen-black requested changes

2023-07-07 20:28 UTC, DeliriumInTheVoid commented on lesson_06/lesson_06.cpp
> +	}
sure ) done with cctype.
I didn't user cctype because it was allowed on the lecture ) please check 52:40 video timing

2023-07-08 05:40 UTC, helen-black requested changes

2023-07-08 05:40 UTC, helen-black commented on lesson_06/lesson_06.cpp
> +		if (islower(input)) {
What if you enter U?

2023-07-08 07:59 UTC, DeliriumInTheVoid commented on lesson_06/lesson_06.cpp
> +		if (islower(input)) {
![image](https://github.com/DeliriumInTheVoid/r_d_cpp_gamedev/assets/11534599/34b5aa5f-62b9-4481-9e86-75e45c461e98)

Everything works according to task. What should be?

2023-07-09 03:33 UTC, helen-black commented on lesson_06/lesson_06.cpp
> +		if (islower(input)) {
It's not a symbol from this case:
Інше (розділові знаки, спецсимвол, тд) - вивести повідомлення, що цей символ не обробляється програмою та продовжити цикл;
You should just print it

2023-07-09 14:55 UTC, DeliriumInTheVoid commented on lesson_06/lesson_06.cpp
> +		if (islower(input)) {
ok, fixed )
but well )) actually it is the symbol for this case. Please read the task thoroughly and you will notice that there is no special condition for char in uppercase. We have:
 - lowercase
 - digit
 - **other** and it means _punctuation marks_, _special character_, **etc**
 So chars in uppercase are in set **etc**

2023-07-10 05:25 UTC, helen-black approved these changes

2023-07-10 05:25 UTC, merged